from services.spotify_service import SpotifyService

spotify_service = SpotifyService()


class PlaylistService:

    def create_musical_dna_playlist(
        self, token: str, track_ids: list, archetype_name: str
    ) -> dict | None:
        playlist_name = "My Musical DNA 🧬"
        description = f"Generated by Sonic Persona — Your {archetype_name} playlist. Curated by AI from your actual listening data."

        # Create playlist
        playlist = spotify_service.create_playlist(
            token, playlist_name, description, public=False
        )
        if not playlist:
            return None

        playlist_id = playlist.get("id")
        playlist_url = playlist.get("external_urls", {}).get("spotify", "")

        # Add tracks
        track_uris = [f"spotify:track:{tid}" for tid in track_ids if tid]
        if track_uris:
            result = spotify_service.add_tracks_to_playlist(token, playlist_id, track_uris)
            if not result:
                return None

        return {
            "playlist_id": playlist_id,
            "playlist_url": playlist_url,
            "name": playlist_name,
            "track_count": len(track_uris),
        }
